# Generated by Django 4.2 on 2024-01-06 02:19

import Cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='Exp_Date',
            field=models.DateField(blank=True, null=True, validators=[Cart.models.validate_mm_yy_date_format]),
        ),
    ]
