# Generated by Django 4.2 on 2024-01-06 02:22

import Cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_creditcard_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='Exp_Date',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[Cart.models.validate_mm_yy_date_format]),
        ),
    ]
