# Generated by Django 4.2 on 2024-01-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_creditcard_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='carreir',
        ),
        migrations.AddField(
            model_name='wallet',
            name='carrier',
            field=models.CharField(blank=True, choices=[('vodafone', 'Vodafone'), ('orange', 'Orange'), ('etisalat', 'Etisalat'), ('we', 'We')], max_length=10, null=True),
        ),
    ]
